### ISSUE TITLE
Idioma e APi

### ISSUE THREAD

**Issue by Root-FTW** [KaiqueBM/fortnite_shop#1]
Desculpe-me por minha escrita, pois só falo espanhol. 

Como posso alterar o idioma do projeto para espanhol 419 e qual PAi você está usando para definir minha própria chave?

---

Peço desculpa pela minha escrita, mas só falo espanhol. 

Como posso alterar a língua do projecto para espanhol 419 , e que PAi está a utilizar para definir a minha própria chave?

**Comment by KaiqueBM** [comment]
Fica na pasta Axios, arquivo config.tsx
Só substituir o "BR" para "ES" na url da API.
baseURL: "https://fortnite-api.com/v2/shop/es"

**Comment by KaiqueBM** [comment]
Só alterar nas urls de chamada da api de "pt-br" para "es-419"
/combined?language=es-419"

**Comment by Root-FTW** [comment]
> Só alterar nas urls de chamada da api de "pt-br" para "es-419"

sim, já o tenho, muito obrigado pelo projecto, tencionam acrescentar mais coisas?

**Comment by KaiqueBM** [comment]
Acho que seria só isso mesmo. Se quiser criar um context para alterar o idioma do site, dar o suporte para ES, seria incrível, que em seguida dou um pull request
